# Generated by Django 2.0.7 on 2018-07-28 20:03

import django.core.validators
from django.db import migrations, models
import partner.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='above_1_2_times_fpl',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address_1',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address_2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='agency_mission',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='agency_types',
            field=models.CharField(blank=True, choices=[('50', '501(c)3'), ('RE', 'Religious Organization'), ('GO', 'Government Organization')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='ages_served',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='at_fpl_or_below',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='case_management',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='currently_provide_diapers',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_of_storage_space',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='diaper_budget',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='diaper_funding_source',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='diaper_use',
            field=models.CharField(blank=True, choices=[('EM', 'Emergency supplies for families (off site)'), ('HO', 'Homeless shelter'), ('DO', 'Domestic violence shelter'), ('ON', 'On-site residential program'), ('OU', 'Outreach'), ('AL', 'Alcohol/Drug Recovery'), ('DA', 'Daycare'), ('FO', 'Foster Care'), ('OT', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='distribution_times',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='distributor_type',
            field=models.CharField(blank=True, choices=[('AG', 'Agency'), ('HO', 'Hospital')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='evidence_based',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='evidence_based_description',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='executive_director_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='executive_director_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='executive_director_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='facebook',
            field=models.CharField(blank=True, help_text='Facebook page name (DO NOT include the URL)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='form_990',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='founded',
            field=partner.fields.RangeIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2017)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='funding_sources',
            field=models.CharField(blank=True, choices=[('FO', 'Grants - Foundation'), ('ST', 'Grants - State'), ('FE', 'Grants - Federal'), ('CO', 'Corporate Donations'), ('IN', 'Individual Donations'), ('OT', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='greater_2_times_fpl',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='incmome_requirement_description',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='income_verification',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='incorporate_plan',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='internal_diaper_bank',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='maac',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='max_serve',
            field=models.IntegerField(blank=True, help_text='Maximum number of people this organization can serve', null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='more_docs_required',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='new_client_times',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='other_diaper_use',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pick_up_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pick_up_contact_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pick_up_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pick_up_method',
            field=models.CharField(blank=True, choices=[('VO', 'Volunteers'), ('ST', 'Staff'), ('CO', 'Courier')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='population_american_indian',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='population_asian',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='population_black',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='population_hispanic',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='population_island',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='population_multi_racial',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='population_other',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='population_white',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='poverty_unknown',
            field=partner.fields.PercentageField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_address1',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_address2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_city',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_client_improvement',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_contact_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_contact_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_description',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='program_zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='proof_of_agency_status',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='proof_of_agency_status_type',
            field=models.CharField(blank=True, choices=[('50', '501(c)3 LETTER'), ('GS', 'Letter of Good Standing from Denominational Headquarters'), ('GL', 'Government Letterhead')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='responsible_staff_position',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='serve_income_circumstances',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='sources_of_diapers',
            field=models.CharField(blank=True, choices=[('PR', 'Purchase Retail'), ('PH', 'Purchase Wholesale'), ('DD', 'Diaper Drives'), ('DO', 'Diaper Drives conducted by others'), ('O', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='storage_space',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='trusted_pickup',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='turn_away_child_care',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter Handle', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='zip_codes_served',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
